export const getHeroStyles = (theme) => ({
  container: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    position: 'relative',
    pt: theme.custom.spacing.xxl,
  },
  parallaxContainer: {
    width: '100%',
    position: 'relative',
  },
  contentBox: {
    maxWidth: '900px',
    mx: 'auto',
    textAlign: 'center',
  },
  japaneseCharacter: {
    fontSize: { xs: '2rem', md: '3.5rem' },
    fontFamily: theme.typography.h1.fontFamily,
    fontWeight: theme.custom.typography.weights.bold,
    mb: theme.custom.spacing.sm,
    opacity: 0.08,
    color: 'primary.main',
    letterSpacing: '0.3em',
  },
  subtitle: {
    color: 'primary.main',
    fontWeight: theme.custom.typography.weights.medium,
    mb: theme.custom.spacing.md,
    letterSpacing: '0.15em',
    textTransform: 'uppercase',
    fontSize: { xs: '0.9rem', md: '1.1rem' },
  },
  nameText: {
    pb: theme.custom.spacing.lg,
    fontSize: { xs: '3rem', sm: '4.5rem', md: '6rem' },
    fontWeight: theme.custom.typography.weights.extraBold,
    fontFamily: theme.typography.h1.fontFamily,
    background: theme.palette.gradient.primary,
    backgroundClip: 'text',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    lineHeight: 1,
    letterSpacing: theme.custom.typography.spacing.loose,
    textShadow: `0 0 80px ${theme.custom.glow.primaryGlow(0.3)}`,
  },
  typeAnimationBox: {
    minHeight: '80px',
    mb: theme.custom.spacing.xl,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  typeAnimationText: {
    color: 'text.secondary',
    fontWeight: theme.custom.typography.weights.light,
    fontSize: { xs: '1.25rem', sm: '1.75rem', md: '2.25rem' },
    fontFamily: '"Satoshi", sans-serif',
  },
  ctaStack: {
    mb: theme.custom.spacing.xl,
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: theme.custom.spacing.md,
  },
  ctaButton: {
    px: theme.custom.spacing.xl,
    py: theme.custom.spacing.sm,
    fontSize: '1.1rem',
    fontWeight: theme.custom.typography.weights.semiBold,
    borderRadius: 0,
    background: theme.palette.gradient.primary,
    boxShadow: `0 8px 32px ${theme.custom.glow.primaryGlow(0.4)}`,
    position: 'relative',
    overflow: 'hidden',
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: '-100%',
      width: '100%',
      height: '100%',
      background: 'linear-gradient(90deg, transparent, rgba(255,255,255,0.3), transparent)',
      transition: `left ${theme.custom.animations.duration.slow}s`,
    },
    '&:hover::before': {
      left: '100%',
    },
    '&:hover': {
      boxShadow: `0 12px 40px ${theme.custom.glow.primaryGlow(0.6)}`,
    },
  },
  outlinedButton: {
    px: theme.custom.spacing.xl,
    py: theme.custom.spacing.sm,
    fontSize: '1.1rem',
    fontWeight: theme.custom.typography.weights.semiBold,
    borderRadius: 0,
    borderWidth: 2,
    borderColor: 'primary.main',
    color: 'primary.main',
    backdropFilter: theme.custom.glassEffect.blur,
    '&:hover': {
      borderWidth: 2,
      background: `linear-gradient(135deg, ${theme.custom.glow.primaryGlow(0.1)}, ${theme.custom.glow.secondaryGlow(0.1)})`,
      borderColor: 'primary.light',
    },
  },
  socialIcon: {
    color: 'text.secondary',
    border: '2px solid',
    borderColor: 'divider',
    borderRadius: 0,
    backdropFilter: theme.custom.glassEffect.blur,
    transition: `color ${theme.custom.animations.duration.normal}s ${theme.custom.animations.easing.default}, border-color ${theme.custom.animations.duration.normal}s ${theme.custom.animations.easing.default}, box-shadow ${theme.custom.animations.duration.normal}s ${theme.custom.animations.easing.default}`,
    '&:hover': {
      color: 'primary.main',
      borderColor: 'primary.main',
      boxShadow: `0 4px 20px ${theme.custom.glow.primaryGlow(0.3)}`,
    },
  },
});
